<a href="https://colab.research.google.com/github/Kimtanyo/ml_lhy_2022spring/blob/main/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [1]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [2]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-1.1229,  0.3348,  0.0324,  0.1006,  0.2694],
        [ 0.6583, -0.7425,  0.5653,  0.3059,  0.5469],
        [-2.0573,  0.3103,  1.5044,  0.0203, -1.5747],
        [-0.7659, -0.4836, -0.4440,  0.0976, -0.7438]])
tensor([[-0.8988, -0.1382,  0.4024,  0.1062,  1.6984],
        [ 0.8200, -1.5864, -1.2335,  1.1205,  2.3812],
        [-0.0128,  0.3485,  1.3173,  0.5510, -0.4633],
        [-0.6639,  0.5710, -0.4671, -0.6187, -0.6185]])
tensor([[-5.7773e-01, -3.5895e-01,  8.8564e-01,  1.7539e-03, -2.0469e+00],
        [-1.0036e+00,  5.2003e-01,  1.1318e+00, -1.5464e+00,  1.0419e+00],
        [ 1.5926e+00,  2.5802e-01,  9.4777e-01,  4.8132e-01, -1.3527e+00],
        [-2.1452e+00,  6.3508e-01,  4.2464e-01,  3.9513e-01, -4.6279e-01]])


In [3]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.5044)


In [4]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([0.6583, 0.3348, 1.5044, 0.3059, 0.5469])
tensor([1, 0, 2, 1, 1])


In [7]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([0.6583, 0.3348, 1.5044, 0.3059, 0.5469])
tensor([1, 0, 2, 1, 1])


In [12]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([0.6583, 0.3348, 1.5044, 0.3059, 0.5469])
tensor([1, 0, 2, 1, 1])


In [28]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[0.6583, 0.3348, 1.5044, 0.3059, 0.5469]])
tensor([[1, 0, 2, 1, 1]])


In [29]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([0.6583, 0.3348, 1.5044, 0.3059, 0.5469])
tensor([1, 0, 2, 1, 1])


<ipython-input-29-5701c508ad13>:3: UserWarning: An output with one or more elements was resized since it had shape [1, 5], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.max(x,0,False,out=p)


In [45]:
m = torch.ones(1,5,dtype=torch.float)
idx = torch.ones(1,5,dtype=torch.long)

In [47]:
# 2-6
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])

tensor([0.6583, 0.3348, 1.5044, 0.3059, 0.5469])
tensor([1, 0, 2, 1, 1])


<ipython-input-47-ec4140db3989>:3: UserWarning: An output with one or more elements was resized since it had shape [1, 5], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.max(x,0,False,out=p)


In [51]:
m = torch.ones(5,dtype=torch.float)
idx = torch.ones(5,dtype=torch.long)

In [73]:
torch.ones(5).long()

tensor([1, 1, 1, 1, 1])

In [52]:
# 2-6
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])

tensor([0.6583, 0.3348, 1.5044, 0.3059, 0.5469])
tensor([1, 0, 2, 1, 1])


In [50]:
# 2-7
m, idx = torch.max(x,True)

TypeError: max() received an invalid combination of arguments - got (Tensor, bool), but expected one of:
 * (Tensor input, *, Tensor out = None)
 * (Tensor input, Tensor other, *, Tensor out = None)
 * (Tensor input, int dim, bool keepdim = False, *, tuple of Tensors out = None)
 * (Tensor input, name dim, bool keepdim = False, *, tuple of Tensors out = None)


In [53]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[-0.8988,  0.3348,  0.4024,  0.1062,  1.6984],
        [ 0.8200, -0.7425,  0.5653,  1.1205,  2.3812],
        [-0.0128,  0.3485,  1.5044,  0.5510, -0.4633],
        [-0.6639,  0.5710, -0.4440,  0.0976, -0.6185]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [54]:
import torch

In [55]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

In [ ]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

RuntimeError: ignored

In [56]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [58]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y = torch.randn(5,4)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [59]:
# 2. mismatched dimensions error (fixed)
y = y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


In [61]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)

OutOfMemoryError: CUDA out of memory. Tried to allocate 7.27 GiB. GPU 0 has a total capacity of 14.75 GiB of which 5.93 GiB is free. Process 2822 has 8.82 GiB memory in use. Of the allocated memory 8.68 GiB is allocated by PyTorch, and 11.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [62]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 1000])


In [70]:
d.unsqueeze(0).shape

torch.Size([1, 3, 244, 244])

In [71]:
# 4. mismatched tensor type error
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

RuntimeError: expected scalar type Long but found Float

In [74]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(1.3434)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [75]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [76]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array.



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [77]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['t']
['y']
['c']
['i']
['s']
['w']
['x']
['r']
['g']
['b']
['o']
['d']
['f']
['q']
['j']
['v']
['z']
['e']
['h']
['a']
['m']
['k']
['l']
['n']
['p']
['u']


A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [78]:
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['R']
['Y']
['S']
['W']
['X']
['l']
['x']
['w']
['b']
['r']
['i']
['g']
['L']
['G']
['a']
['c']
['F']
['v']
['J']
['N']
['m']
['V']
['Z']
['k']
['O']
['U']
['p']
['B']
['D']
['t']
['Q']
['E']
['h']
['I']
['j']
['q']
['H']
['u']
['P']
['d']
['C']
['y']
['T']
['f']
['s']
['K']
['n']
['o']
['A']
['M']
['e']
['z']
